name: Build and Push to Heroku

on:
  push:
    branches:
      - production
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint using ESlint
        run: |
          npm run lint

      - name: Test with Jest & Supertest
        run: |
          npm run test

  build-and-push:
    needs: test
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # This block will deploy the docker container to heroku
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: '.'

      # This block will deploy the docker container to docker hub
      # This will require setting up some kind of watchtower through a service
      # like Digital Ocean.
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      #
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: ./Dockerfile
      #     tags: dinomartinez/express-quickstart:latest
      #     push: true
